#KubeJS Dev Properties
#Sun Apr 19 00:25:18 MSK 2026
alwaysCaptureErrors=false
dataPackOutput=false
debugInfo=false
logAddedRecipes=false
logErroringRecipes=true
logGeneratedData=false
logInvalidRecipeHandlers=true
logModifiedRecipes=false
logRemovedRecipes=false
logSkippedPlugins=true
logSkippedRecipes=false
logSkippedTags=false
strictTags=false
