#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri Jun 19 18:01:04 MSK 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=VanillaPlus_v3.3.zip
enableShaders=true
